spring.application.name=demo
# App Configuration
server.port=8082

# Spring AI Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
# Explicitly specifying the lightweight model we downloaded
spring.ai.ollama.chat.options.model=llama3.2:1b